"""Stubs del módulo nativo (Rust). La API pública está en `hivedb`."""

from typing import Any, Callable, Iterator, Optional

ERROR_CODES: dict[str, str]

class HiveDBError(Exception):
    code: Optional[str]

class Subscription(Iterator[dict[str, Any]]):
    def next(self, timeout: Optional[float] = None) -> Optional[dict[str, Any]]: ...
    def close(self) -> None: ...
    def __iter__(self) -> "Subscription": ...
    def __next__(self) -> dict[str, Any]: ...

class Database:
    @staticmethod
    def open(path: str, options: Optional[dict[str, Any]] = None) -> "Database": ...
    def append(self, input: dict[str, Any]) -> int: ...
    def read(self, seq: int) -> dict[str, Any]: ...
    def log_len(self) -> int: ...
    def last_seq(self) -> int: ...
    def tool_stats(
        self, tool: str, agents: Optional[list[str]] = None
    ) -> Optional[dict[str, Any]]: ...
    def project_task_state(self, agent_id: str, stream_id: str) -> Optional[str]: ...
    def can(self, agent: str, action: str, resource: str) -> dict[str, Any]: ...
    def working_set(
        self, agent_id: str, key: str, value: Any, ttl_ms: Optional[int] = None
    ) -> None: ...
    def working_get(self, agent_id: str, key: str) -> Any: ...
    def working_keys(self, agent_id: str) -> list[str]: ...
    def causal_thread(self, stream_id: str, agents: Optional[list[str]] = None) -> Any: ...
    def build_agent_context(self, request: dict[str, Any]) -> Any: ...
    def upsert_doc(self, doc: dict[str, Any]) -> None: ...
    def upsert_batch(self, docs: list[dict[str, Any]]) -> None: ...
    def delete_doc(self, id: str) -> None: ...
    def delete_by_filter(self, filter: dict[str, Any]) -> None: ...
    def clear_index(self) -> None: ...
    def compact_index(self) -> None: ...
    def query_hybrid(self, query: dict[str, Any]) -> list[dict[str, Any]]: ...
    def trace_vector(
        self, vector: list[float], k: int, ef_search: Optional[int] = None
    ) -> dict[str, Any]: ...
    def col_put(
        self, collection: str, id: str, doc: Any, expected_version: Optional[int] = None
    ) -> int: ...
    def col_get(self, collection: str, id: str) -> Optional[dict[str, Any]]: ...
    def col_delete(self, collection: str, id: str) -> bool: ...
    def col_scan(
        self, collection: str, options: Optional[dict[str, Any]] = None
    ) -> list[dict[str, Any]]: ...
    def col_count(self, collection: str) -> int: ...
    def col_create_index(self, collection: str, field: str, unique: bool = False) -> None: ...
    def col_find_by(
        self, collection: str, field: str, value: Any, options: Optional[dict[str, Any]] = None
    ) -> list[dict[str, Any]]: ...
    def col_batch(self, ops: list[dict[str, Any]]) -> None: ...
    def subscribe(self, pattern: dict[str, Any]) -> Subscription: ...
    def close(self) -> None: ...

def prepare_embedder(
    on_progress: Optional[Callable[[dict[str, Any]], None]] = None,
) -> dict[str, Any]: ...
def evaluate_harness(input: dict[str, Any]) -> Any: ...
